trigger:
- main

pool:
  name: Default

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'DockerHub'  # Azure DevOps service connection to Docker Hub
    repository: 'sidj5297/weather-app'  # Docker Hub repository name
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'  # Path to the Dockerfile
    tags: 'latest'  # Tags for the Docker image
    
- script: |
    ansible-playbook -i inventory.yaml playbook.yaml
